"""
Django settings for booking_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import base64
import json as _json
import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# This tells Django to read  .env file so  Google credentials become available.
env = environ.Env()

# Always load secrets
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Then overlay environment-specific URLs
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")
env_file = ".env.production" if DJANGO_ENV == "production" else ".env.development"
env_file_path = os.path.join(BASE_DIR, env_file)
if os.path.exists(env_file_path):
    environ.Env.read_env(env_file_path)

FRONTEND_URL = env("FRONTEND_URL")
GOOGLE_OAUTH2_CLIENT_ID = env("GOOGLE_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DJANGO_ENV != "production"

ALLOWED_HOSTS = [
    "pairscheduler-backend.hosting.codeyourfuture.io",
    "localhost",
    "127.0.0.1",
    "backend",
]


# Application definition
# Adding authentication app to settings

INSTALLED_APPS = [
    # -------------------------------
    # Default Django apps
    # -------------------------------
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # -------------------------------
    # Third‑party apps
    # -------------------------------
    "corsheaders",  # Handles Cross-Origin Resource Sharing (CORS)
    # -------------------------------
    # Django Allauth / Social Login apps
    # -------------------------------
    "django.contrib.sites",  # Required by allauth (site framework)
    "allauth",  # Core allauth app
    "allauth.account",  # Handles login, signup, email verification
    "allauth.socialaccount",  # Enables social login functionality
    "allauth.socialaccount.providers.google",  # Google OAuth provider
    # -------------------------------
    # Your project apps
    # -------------------------------
    "core",  # app for project calendar logic
    "auth_app",  # Custom authentication app (must come AFTER allauth)
    "rest_framework",  # Django REST Framework to interact with frontend React.
]

# -------------------------------
# Site framework setting (required by django-allauth)
# -------------------------------
# This tells Django which Site object to use (from the Sites framework)
SITE_ID = 1

# to connect allauth to the values in  .env.
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
    }
}

LOGIN_REDIRECT_URL = f"{FRONTEND_URL}/"
ACCOUNT_LOGIN_REDIRECT_URL = f"{FRONTEND_URL}/"
LOGOUT_REDIRECT_URL = f"{FRONTEND_URL}/"
ACCOUNT_LOGOUT_REDIRECT_URL = f"{FRONTEND_URL}/"


# This makes sure Google login actually fills the email in the user record.
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # for dev

# skip the "social login confirmation" djnago default page
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # CSRF MUST come after CommonMiddleware
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "booking_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "booking_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv("POSTGRES_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# To stop using the default user and look at ours instead
AUTH_USER_MODEL = "core.User"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Google Calendar integration settings with cyf service account
# "primary" means "use the service account's main calendar"
GOOGLE_CALENDAR_ID = "primary"
GOOGLE_SERVICE_ACCOUNT_FILE = BASE_DIR / "secrets/cyf-service-account.json"

# If GOOGLE_SERVICE_ACCOUNT_JSON is set (base64-encoded JSON), use it directly.
# Otherwise fall back to reading the file above (dev/Docker with file mount).
_sa_json_b64 = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
GOOGLE_SERVICE_ACCOUNT_INFO = (
    _json.loads(base64.b64decode(_sa_json_b64)) if _sa_json_b64 else None
)


# Adding cors settings
CORS_ALLOWED_ORIGINS = list(
    {
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
        FRONTEND_URL,
    }
)
CORS_ALLOW_CREDENTIALS = True

# send logs to the console

# show INFO, WARNING, ERROR, CRITICAL

# include your module logs
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "": {  # root logger
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}
# Adding this ID as are service account user which will act as a bot to generate emails for us.
GOOGLE_IMPERSONATED_USER_EMAIL = "automated@codeyourfuture.io"

# -------------------------------
# Authentication backends (required by allauth)
# -------------------------------
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default Django authentication
    "allauth.account.auth_backends.AuthenticationBackend",  # Needed for allauth(Google to work)
]

CSRF_TRUSTED_ORIGINS = list(
    {
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://127.0.0.1:5174",
        FRONTEND_URL,
    }
)

if DJANGO_ENV == "production":
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}
