# Generated by Django 4.2.29 on 2026-03-27 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('itd', 'ITD'), ('itp', 'ITP'), ('piscine', 'Piscine'), ('sdc', 'SDC'), ('the_launch', 'The Launch')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SlotRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('group', models.CharField(blank=True, choices=[('itd', 'ITD'), ('itp', 'ITP'), ('piscine', 'Piscine'), ('sdc', 'SDC'), ('the_launch', 'The Launch')], max_length=20, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['volunteer_id', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('google_meet_link', models.CharField(max_length=100)),
                ('agenda', models.CharField(blank=True, max_length=500, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_trainee', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_volunteer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('volunteer', 'start_time'), name='constraint_unique_volunteer_datetime'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('trainee', 'start_time'), name='constraint_unique_trainee_datetime'),
        ),
    ]
