# Generated by Django 4.2.29 on 2026-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_full_name_remove_user_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotrule',
            name='group',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('itd', 'ITD'), ('itp', 'ITP'), ('piscine', 'Piscine'), ('sdc', 'SDC'), ('the_launch', 'The Launch')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('itd', 'ITD'), ('itp', 'ITP'), ('piscine', 'Piscine'), ('sdc', 'SDC'), ('the_launch', 'The Launch')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
