# Generated by Django 4.2.29 on 2026-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='google_meet_link',
            field=models.CharField(max_length=128),
        ),
    ]
