# Generated by Django 4.2.29 on 2026-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_google_meet_link'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slotrule',
            constraint=models.UniqueConstraint(fields=('volunteer', 'start_time'), name='unique_volunteer_start_time_slot_rule'),
        ),
    ]
