# Generated by Django 4.2.29 on 2026-04-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_slotrule_unique_volunteer_start_time_slot_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.slotrule'),
        ),
    ]
