# Generated by Django 4.2.29 on 2026-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_slot_rule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slotrule',
            name='unique_volunteer_start_time_slot_rule',
        ),
        migrations.AddField(
            model_name='slotrule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='slotrule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('volunteer', 'start_time'), name='unique_volunteer_start_time_slot_rule'),
        ),
    ]
