# Generated by Django 6.0.3 on 2026-07-16 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_id_alter_slotrule_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotruleexception',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='slotruleexception',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='slotruleexception',
            name='date',
        ),
    ]
