# Generated by Django 6.0.3 on 2026-07-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_slotruleexception_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotruleexception',
            unique_together={('slot_rule', 'start_time')},
        ),
    ]
